#apiVersion: v1
#kind: Service
#metadata:
#  name: health-check-service
#  namespace: health-check
#spec:
#  type: NodePort
#  ports:
#  - port: 3000
#  selector:
#    app: node-hello-world-app
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world-deployment
  namespace: health-check
  labels:
    app: node-hello-world-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-hello-world-app
  template:
    metadata:
      labels:
        app: node-hello-world-app
    spec:
      containers:
      - name: node-hello-world-app-container
        image: abdulrehman2861/nodejs_docker_example:latest
        ports:
          - name: web
            containerPort: 3000
      imagePullSecrets:
          - name: regcred
